  default: &default
    adapter: sqlite3
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: hogehoge
    password: password
    host: localhost

  development:
    <<: *default
    database: jiro_log_development

  test:
    <<: *default
    database: jiro_log_test

  production:
    <<: *default
    database: jiro_log_production
   # username: hogehoge
   # password: <%= ENV['jiro_log_DATABASE_PASSWORD'] %>
